spring: 
  profiles: 
    ## 开发/测试/生产环境 dev/test/prod
    active: dev    
  aop:
    proxy-target-class: true
    auto: true
  mvc:
    static-path-pattern: /static/**
  ##上传文件大小限制
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb              
  application:
#    name: gdjtic
    name: tysoft
  thymeleaf:
      cache: false
   ##日志配置   
logging:
  file: D:/tysoft_oa/log/tysoft-log.log
  level: 
    org.hibernate: warn
    com.microsoft: warn
  
server: 
  port: 8181
  context-path: /${spring.application.name}
  

    
    
